### PR TITLE
Add an option to not fork when creating a pull request

### LINKED ISSUE #37: I'd like to pull request to the same repo. I don't want to create a fork.
I tried messing with the code but I got errors. 
Is it hard to have a option to not fork?

### PR DESCRIPTION
**Pull request by therve**
This creates a branch in the origin repository instead.

Fixes #37

### CODE REVIEW

**Comment by therve** [comment]
Absolutely not tested, please check it out.

**Comment by therve** [comment]
Pull-request updated, HEAD is now 25c21dcc99540e2f4022d6d5127e65a57514ded8

**Comment by jd** [comment]
@therve I've fixed the pep8 error in master, if you can just rebase that should be fine now.

**Comment by therve** [comment]
Pull-request updated, HEAD is now 83dc74e6dfbd5b3d5a2535186e531bbaa3f57717

**Comment by therve** [comment]
Pull-request updated, HEAD is now ba21b286bb75a879f07122bf951bdfc0970a82cb

**Pull request merged**
